#ifndef _PRIVMXLIB_ENDPOINT_STORE_STOREVARDESERIALIZER_HPP_
#define _PRIVMXLIB_ENDPOINT_STORE_STOREVARDESERIALIZER_HPP_

#include <privmx/endpoint/core/VarDeserializer.hpp>

#endif  // _PRIVMXLIB_ENDPOINT_STORE_STOREVARDESERIALIZER_HPP_
