name: Tests Unit

on:
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install CMake and Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcomposite1 libxdamage1 libxrandr2 libgbm1 cmake pipx
        sudo pipx install conan
        echo "/root/.local/bin" >> $GITHUB_PATH

    - name: Setup virtual audio device
      run: |
        sudo apt-get install -y pulseaudio libasound2-plugins
        pulseaudio --start --exit-idle-time=-1

    - name: Setup conan
      run: |
        conan profile detect --force
        conan remote add privmx ${{ vars.CONAN_ARTIFACTORY }}

    - name: Conan Remote Auth
      run: conan remote login -p "${{ secrets.CONAN_PASSWORD }}" privmx "${{ vars.CONAN_USER }}"

    - name: Build library
      run: ./build-with-streams.sh

    - name: Upload binaries
      run: conan upload "*" --remote=privmx --confirm

    - name: Run Unit tests
      run: |
        source build/build/Debug/generators/conanrun.sh
        ./scripts/run_tests.sh --unit-only --build-dir "build" --dataset-dir "test/test_env/create_dataset/Dataset"
